### ISSUE TITLE
how to load custom dosbox.conf in dosbox-loader

### ISSUE THREAD

**Issue by veso266** [db48x/emdosbox-loader#2]
Hi I would like to know how can I load custom dosbox.conf in emdosbox-loader

I was using this code to load file from zip
`     var emulator = new Emulator(document.querySelector("#canvas"),
                                  null,
                                  new DosBoxLoader(DosBoxLoader.emulatorJS("emulator/dosbox.js"),
                                                   DosBoxLoader.nativeResolution(640, 400),
                                                   DosBoxLoader.mountZip("c",
                                                                         DosBoxLoader.fetchFile("Game File",
                                                                                                "emulator/win311-stock.zip")),
                                                   DosBoxLoader.startExe("windows.bat")))
      emulator.start({ waitAfterDownloading: true });
` 
now I also have dosbox.conf in my zip so how can I load it in so emdosbox will recognize it?

Thanks for Anwsering and Best Regards

**Comment by db48x** [comment]
Closing this one in favor of [the one over on the Emularity](https://github.com/db48x/emularity/issues/13)
